export const globalStrings = {
  linkedIn: 'https://www.linkedin.com/in/derek-andrews-5280/',
  allBreeds: 'https://dog.ceo/api/breeds/list/all',
  imageUrl: 'https://dog.ceo/api/breed/selected/images',
  resumeUrl: 'https://www.derekwebdev.com/derek_andrews_resume.pdf',
  spiral: 'https://www.derekwebdev.com/spiral/index.html',
  webviewError: 'There has been a rendering error',
  browserUrl: 'https://derekwebdev.com',
  browserUrlFull: 'www.DerekWebDev.com',
  showBreeds: 'Show Breeds!',
  viewResume: 'View Resume',
  stringWithSpace: ' ',
  emptyString: '',
  slash: '/',
  hideBreeds: 'Hide Breeds!',
  netWorkError: ' Something went wrong: ',
  selected: 'selected',
  dashBoard: 'Dashboard',
  searchDogs: 'Search dogs...',
  pleaseWait: 'Please Wait...',
  presentedBy: 'Presented by DerekWebDevⓒ',
  allThings: 'Your source for all things dog!',
  skipLogin: 'Skip Login',
  goBack: 'Logout',
  alertWarning: 'Please use only letters or simply browse our list below.',
  dogsApp: 'Welcome to DogsApp®',
  author: 'Derek Andrews',
  profile: 'Profile',
  emailAddress: 'info@DerekWebDev.com',
  emailAddressLink: 'mailto:info@derekwebdev.com',
  privacyNumber: '720-206-****',
  linkedInShort: 'Derek-Andrews-5280',
  phoneNumber: '7202069184',
  text: 'Send a text',
  uploadTitle: 'Take or browse photos of your doggy.',
  camera: 'Camera',
  gallery: 'Gallery',
  upLoad: 'Upload',
  regex: /[!@#$%^&*(),.?":{}|<>0-9/]/gi,
};

export const globalColors = {
  paletteLight: '#FFC4C4',
  palettePink: '#EE6983',
  paletteLightText: '#FFF5E4',
  shadowBackground: 'rgba(0,0,0,0.6)',
  shadowBackgroundPink: 'rgba(238, 105, 131, 0.5)',
  shadowBackGroundPinkDarker: 'rgba(238, 105, 131, 0.8)',
  tabActiveTint: '#850E35',
  tabInactiveTint: '#FFC4C4',
};

export enum globalEnums {
  large = 'large',
  success = 'success',
  camera = 'camera',
  doubleRight = 'doubleright',
  doubleLeft = 'doubleleft',
  user = 'user',
  homeOutline = 'home-outline',
  closeCirle = 'closecircleo',
  externalLink = 'external-link',
  email = 'email',
  mail = 'mail',
  phone = 'call-outline',
  linkedIn = 'linkedin-square',
  eye = 'eye',
  smartphone = 'smartphone',
}
